import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";
import { Loader2, ArrowLeft, Upload } from "lucide-react";

interface ServiceCategory {
  id: string;
  name_ru: string;
  name_en: string;
  name_tj: string;
  icon: string;
}

export default function QuickOrder() {
  const navigate = useNavigate();
  const location = useLocation();
  const { language } = useLanguage();
  const [loading, setLoading] = useState(false);
  const [categories, setCategories] = useState<ServiceCategory[]>([]);
  const [user, setUser] = useState<any>(null);

  const [formData, setFormData] = useState({
    category_id: "",
    object_type: "",
    district: "",
    address: "",
    preferred_time: "",
    comment: "",
    budget: "",
  });

  useEffect(() => {
    checkAuth();
    loadCategories();

    // If repeating an order, pre-fill the form
    if (location.state?.repeatOrder) {
      const order = location.state.repeatOrder;
      setFormData({
        category_id: order.category_id,
        object_type: order.object_type,
        district: order.district,
        address: order.address,
        preferred_time: order.preferred_time,
        comment: order.comment || "",
        budget: order.budget,
      });
    }
  }, [location.state]);

  const checkAuth = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    
    if (!user) {
      toast.error("Для создания заказа необходимо войти");
      navigate("/auth");
      return;
    }

    setUser(user);
  };

  const loadCategories = async () => {
    try {
      const { data, error } = await supabase
        .from("service_categories")
        .select("*")
        .order("sort_order");

      if (error) throw error;
      setCategories(data || []);
    } catch (error) {
      console.error("Error loading categories:", error);
    }
  };

  const getCategoryName = (category: ServiceCategory) => {
    switch (language) {
      case "en": return category.name_en;
      case "tj": return category.name_tj;
      default: return category.name_ru;
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (!user) {
        throw new Error("Необходимо войти");
      }

      const { error } = await supabase.from("orders").insert({
        user_id: user.id,
        category_id: formData.category_id,
        object_type: formData.object_type,
        district: formData.district,
        address: formData.address,
        preferred_time: formData.preferred_time,
        comment: formData.comment,
        budget: formData.budget,
        order_number: "", // Will be auto-generated by trigger
      });

      if (error) throw error;

      toast.success("Заказ успешно создан!");
      navigate("/my-orders");
    } catch (error: any) {
      toast.error(error.message || "Ошибка создания заказа");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const objectTypes = ["Квартира", "Дом", "Офис", "Магазин", "Ресторан / кафе", "Склад"];
  const districts = ["Сино", "Фирдауси", "Шохмансур", "Исмоили Сомони", "Пригород Душанбе", "Другое"];
  const timeSlots = ["Сегодня до 14:00", "Сегодня после 14:00", "Завтра", "Выбрать дату/время"];
  const budgetOptions = ["До 200", "До 500", "Обсудим", "Не знаю"];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-secondary/20 to-background py-8">
      <div className="container px-4 max-w-3xl">
        <div className="flex items-center gap-4 mb-8">
          <Button variant="outline" onClick={() => navigate("/")} className="gap-2">
            <ArrowLeft className="w-4 h-4" />
            На главную
          </Button>
          <h1 className="text-3xl font-bold gradient-hero bg-clip-text text-transparent">
            Быстрый заказ
          </h1>
        </div>

        <Card className="shadow-2xl">
          <CardHeader>
            <CardTitle>Создать заявку</CardTitle>
            <CardDescription>
              Заполните форму, и мы подберём для вас мастера
            </CardDescription>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="category">Категория услуги *</Label>
                <Select
                  value={formData.category_id}
                  onValueChange={(value) => setFormData({ ...formData, category_id: value })}
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Выберите категорию" />
                  </SelectTrigger>
                  <SelectContent>
                    {categories.map((category) => (
                      <SelectItem key={category.id} value={category.id}>
                        <span className="flex items-center gap-2">
                          <span>{category.icon}</span>
                          <span>{getCategoryName(category)}</span>
                        </span>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="object_type">Тип объекта *</Label>
                <Select
                  value={formData.object_type}
                  onValueChange={(value) => setFormData({ ...formData, object_type: value })}
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Выберите тип" />
                  </SelectTrigger>
                  <SelectContent>
                    {objectTypes.map((type) => (
                      <SelectItem key={type} value={type}>{type}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="district">Район *</Label>
                <Select
                  value={formData.district}
                  onValueChange={(value) => setFormData({ ...formData, district: value })}
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Выберите район" />
                  </SelectTrigger>
                  <SelectContent>
                    {districts.map((district) => (
                      <SelectItem key={district} value={district}>{district}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="address">Адрес *</Label>
                <Input
                  id="address"
                  placeholder="Улица Рудаки, дом 123, кв. 45"
                  value={formData.address}
                  onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                  required
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="preferred_time">Желаемое время *</Label>
                <Select
                  value={formData.preferred_time}
                  onValueChange={(value) => setFormData({ ...formData, preferred_time: value })}
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Когда удобно?" />
                  </SelectTrigger>
                  <SelectContent>
                    {timeSlots.map((slot) => (
                      <SelectItem key={slot} value={slot}>{slot}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="budget">Бюджет *</Label>
                <Select
                  value={formData.budget}
                  onValueChange={(value) => setFormData({ ...formData, budget: value })}
                  required
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Выберите бюджет" />
                  </SelectTrigger>
                  <SelectContent>
                    {budgetOptions.map((budget) => (
                      <SelectItem key={budget} value={budget}>{budget}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="comment">Комментарий (опционально)</Label>
                <Textarea
                  id="comment"
                  placeholder="Опишите проблему или дополнительные детали..."
                  value={formData.comment}
                  onChange={(e) => setFormData({ ...formData, comment: e.target.value })}
                  rows={4}
                />
              </div>

              <Button type="submit" className="w-full" size="lg" disabled={loading}>
                {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                Создать заказ
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}